services:
  api:
    environment:
      - NODE_ENV=development  # 允许通过 HTTP 传输 Cookie, 避免不能带上cookie导致要重登
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
    ports:
      - "80:${PORT}"  # 将容器的 PORT 端口映射到主机的 80 端口
    command: node api/server/index.js  # 直接使用 node 启动，不通过 npm run backend